### ISSUE TITLE
Package not published

### ISSUE THREAD

**Issue by Alex-CS** [paramander/contentful-rich-text-vue-renderer#1]
Hey! I'd love to use this, but it doesn't seem to be published on NPM.

```
✗ npm install contentful-rich-text-vue-renderer
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/contentful-rich-text-vue-renderer - Not found
npm ERR! 404
npm ERR! 404  'contentful-rich-text-vue-renderer@latest' is not in the npm registry.
```

**Comment by tolgap** [comment]
@Alex-CS Correct, I have published it as a private NPM package.

I haven't had time to clean the codebase up. That's why I hadn't published it yet. I'll give it a shot at publishing it today.

**Comment by tolgap** [comment]
@Alex-CS I have published the package. It's very basic as is, but I hope you can at least get to work with rendering the content 👍 .

**Comment by Alex-CS** [comment]
Thanks! This level of simplicity is actually exactly what we're looking for. I had started building something on top of Contentful's own `rich-text-html-renderer`, but I really like how transparent yours is.

**Comment by tolgap** [comment]
@Alex-CS thanks for the kind words!

If you see any improvements, let us know in the issues. Or if you wish to take a crack at it yourself, feel free to open a PR 👍.
