### ISSUE TITLE
Multiple marks not rendering

### ISSUE THREAD

**Issue by matthew-inamdar** [paramander/contentful-rich-text-vue-renderer#11]
Hi there 👋

I want to start by acknowledging how great this package is! Thank you for your work on it.

I've run into an issue where a node with multiple marks is not being rendered. In my example, I have a paragraph with text that is both bold and underlined.

The result is that the text is not displayed at all.

Any help or advice would be fantastic; I can also provide code snippets if needed.

**Comment by tolgap** [comment]
Hi Matthew, thanks for the kind words.

If you could provide the snippet, I might be able to reproduce it.

**Comment by tolgap** [comment]
@matthew-inamdar I managed to reproduce your issue. The fix has been released as `v1.1.5`

**Comment by matthew-inamdar** [comment]
Thanks @tolgap 👍
