### ISSUE TITLE
Passing props to custom element

### ISSUE THREAD

**Issue by damienroche** [paramander/contentful-rich-text-vue-renderer#15]
Hi,
I would like to display EMBEDDED_ASSET, within the Contenful Deliver API I can only get the asset id.
So I have to load a custom component like this :
```
[BLOCKS.EMBEDDED_ASSET]: (node, key, h, next) => {
      return h('contentful-asset', { key, id: node.data.target.sys.id })
    }
```
On my ContenfulAssset component I will make a request to retrieve asset url.
But the prop doesn't seems to be passed to the custom component.

I used the same syntax of your documentation

> return h('Link', { key: key, to: 'link to embedded entry' }, 'content for the <Link> component');

**Comment by tolgap** [comment]
Hi Damien,

I assume you are trying to pass in the `id` prop. If you're trying to use the `h` method, this is also called `createElement` in Vue: https://vuejs.org/v2/guide/render-function.html#createElement-Arguments .

**Comment by bilelz** [comment]
Hello,
@damienroche, you can write this: 
```
[BLOCKS.EMBEDDED_ASSET]: (node, key, h, next) => {
  return h('contentful-asset', {
    key,
    props: { id: node.data.target.sys.id },
  });
},
```

**Comment by damienroche** [comment]
thanks @bilelz

**Comment by tolgap** [comment]
I'll close this issue as the example should fix it.
