### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by michalpaukert** [paramander/contentful-rich-text-vue-renderer#18]
Will this package support Vue3?

**Comment by tolgap** [comment]
Seems like there were significant changes to functional components in Vue 3. As in, functional components are removed.

This will need a breaking update. I'll try looking into this on a weekend.

**Comment by tolgap** [comment]
I have just releases `v3.0.0-rc.0` for Vue 3 support. Please give it a try and if there are any issues, please open a new issue so this one doesn't fill up with multiple/various issues.

It's a pre-release so I wouldn't recommend immediately dropping it into a production codebase and deploying it.
