### ISSUE TITLE
Break support

### ISSUE THREAD

**Issue by michalpaukert** [paramander/contentful-rich-text-vue-renderer#29]
Regarding new post on contetnful I would like to support `<br />`
https://www.contentful.com/blog/2021/05/27/rich-text-field-tips-and-tricks/

**Comment by tolgap** [comment]
See this spec as an example on how to do it: https://github.com/paramander/contentful-rich-text-vue-renderer/blob/master/src/index.test.js#L451

**Comment by NWRichmond** [comment]
Hi @michalpaukert, I made [a Code Sandbox](https://codesandbox.io/s/delicate-shadow-81xs7?file=/src/App.vue) to demonstrate @tolgap's example of [using `nodeRenderers` to render a `<br />`](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/6b21fcf23ba6904235c70d389f315df0bfe13c5c/src/index.test.js#L403-L426).

I hope you find it helpful!

<img width="512" alt="Screen Shot 2021-07-09 at 7 06 06 PM" src="https://user-images.githubusercontent.com/5732000/125143438-b9d96a00-e0e8-11eb-9921-1aa60ec62f2c.png">

One thing that I had trouble with at first...as demonstrated in the Code Sandbox, in addition to the `[BLOCKS.SOMETHING]`s, be sure to include:

```js
break: (_node, key, h) => h("br", key, {}),
```

in the object passed to the `node-renderers` prop.

**Comment by NWRichmond** [comment]
One issue with the `<br />`-supporting `nodeRenderers` from [`/src/index.test.js`](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/6b21fcf23ba6904235c70d389f315df0bfe13c5c/src/index.test.js#L403-L426) that are demonstrated in [the Code Sandbox](https://codesandbox.io/s/delicate-shadow-81xs7?file=/src/App.vue) is that they cause Vue to warn:

> [Vue warn]: You may have an infinite update loop in a component render function.

I tested this outside of Code Sandbox (in a Nuxt project) and got the same warning.

@tolgap if you have any suggestions about how to resolve that warning , please share them! And thank you for your work on this project 🙏

---

UPDATE: I created #33 after demonstrating issues during SSG w/Nuxt - it's more than a superficial console warning, and probably warrants being its own issue.
