### ISSUE TITLE
Not working on nuxt3

### ISSUE THREAD

**Issue by bootsmann1995** [paramander/contentful-rich-text-vue-renderer#43]
The rich text renderer is not working on nuxt 3? is it possible to make this asap?

**Comment by tolgap** [comment]
@bootsmann1995 which version are you using. There is a preview version for Vue 3 `contentful-rich-text-vue-renderer@next`. If you're already on this version: do you have an error or a reproduction of this error?

**Comment by bootsmann1995** [comment]
Hey, i rewrote your component. It was missing a small thing to work in nuxt3. 

Your export default was changed to export default defineNuxtComponent(…

plus i added some more strong types to props. I Can send the version if you want?

**Comment by tolgap** [comment]
@bootsmann1995 this library is not for Nuxt specific code. This is a Vue component only.

**Comment by bootsmann1995** [comment]
Okay, no problem. Only if you wanted to add a nuxt module for it.
